# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abe2a7abf81dac5eef25e8a52d7293bea928062a3805edaac9d30553a5b2ccc0a188a7cb5a5b8da6add0039698bf752d3cfbedc644a28a55e6bf1eb107543292

test:
  secret_key_base: 073bbb75a7015b613ab14c125a41918d1749b04a2f29af05f110156be4bf975ae1717011b112ba858b29f23c540b0217a8779ef8d0e697ea19019b4a90ca723e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
